# Site settings
title: 2016 PUI Lab
description: Website for 2016 PUI Lab
baseurl: /2016PUI
url: "http://www.siyanz.com/" # the base hostname & protocol for your site
#favicon
favicon: /favicon.png


#google analytics
google_analytics_id : 

#fb_username
fb_username: 

permalink: /:path
# Build settings
markdown: kramdown

remarkConfig:
  # possible highlight options:
  # arta, ascetic, dark, default, far, github, googlecode, idea, ir_black,
  # magula, monokai, rainbow, solarized-dark, solarized-light, sunburst,
  # tomorrow, tomorrow-night-blue, tomorrow-night-bright, tomorrow-night,
  # tomorrow-night-eighties, vs, zenburn.
  highlightStyle: 'default'
  highlightLanguage: 'remark'
  highlightLines: true

collections:
  slides:
      layout: remark
      permalink: /slides/:path/
      output: true


#Disqus configuration
disqus_short_name: 
disqus_show_comment_count:

#Can be used for multiple author blogs ! Add name to post For more visit the sample
authors:
  siyanz:
    display_name: Siyan Zhao
    email: siyanz@andrew.cmu.edu
    github: siyanz
  annak:
    display_name: Anna Kanustic
    email:
    github:
